[features]
seeds = false
skip-lint = false

[programs.devnet]
avatos_nft = "6CjY9JxNbd1o16Q53cu67TeD7xwwcGiLYSUdgDJ9jHpi"

[programs.localnet]
avatos_nft = "6CjY9JxNbd1o16Q53cu67TeD7xwwcGiLYSUdgDJ9jHpi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"                      # "Devnet"
wallet = "~/.config/solana/violet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "npx ts-node ./scripts/deploy_and_init.ts"
mint = "npx ts-node ./scripts/mint_nft.ts"
verify = "npx ts-node ./scripts/verify_nft.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
